In [1]:
# import relevant libraries
import sys,os
from pathlib import Path
import pandas as pd
import matplotlib

# import own modules
sys.path.append(str(Path.cwd().parent))
from utils.data_practice_level import read_practice_data
from utils.variables import PATH_gp_practice, PATH_gp_practice_jupyter

# import raw data

In [2]:
data = read_practice_data(path=PATH_gp_practice_jupyter)

In [3]:
data.describe()

,TOTAL_PATIENTS,TOTAL_GP_HC,TOTAL_GP_FTE,TOTAL_GP_HC_COQ_UK,TOTAL_GP_HC_COQ_EEA,TOTAL_GP_HC_COQ_EUROPE_OTHER,TOTAL_GP_HC_COQ_AFRICA,TOTAL_GP_HC_COQ_ASIA_OTHER,TOTAL_GP_HC_COQ_ASIA_SOUTH,TOTAL_GP_HC_COQ_AUS_PAC,TOTAL_GP_HC_COQ_CEN_AMERICA,TOTAL_GP_HC_COQ_NORTH_AMERICA,TOTAL_GP_HC_COQ_SOUTH_AMERICA,TOTAL_GP_HC_COQ_MIDDLE_EAST,TOTAL_GP_HC_COQ_UNKNOWN
count,6149.000000,6095.000000,6095.000000,6095.000000,6095.000000,6095.000000,6095.000000,6095.000000,6095.000000,6095.000000,6095.000000,6095.000000,6095.000000,6095.000000,6095.000000
mean,10315.916084,8.469401,6.208911,5.745693,0.371616,0.092535,0.730599,0.094011,1.091715,0.013618,0.048728,0.005906,0.014602,0.125513,0.134865
std,7199.862705,6.330054,4.678151,5.205521,0.670941,0.319432,1.176264,0.318227,1.431612,0.118705,0.225735,0.076633,0.119964,0.375003,0.639364
min,0.000000,1.000000,0.053333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5869.000000,4.000000,2.805200,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,8804.000000,7.000000,5.235467,5.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,12713.000000,11.000000,8.385600,8.000000,1.000000,0.000000,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,118685.000000,93.000000,59.546667,85.000000,6.000000,4.000000,11.000000,3.000000,13.000000,2.000000,2.000000,1.000000,1.000000,4.000000,16.000000

In [4]:
data[data.TOTAL_PATIENTS==0].shape

(26, 18)

In [11]:
data[data.TOTAL_GP_HC==93]

,PRAC_CODE,PRAC_NAME,TOTAL_PATIENTS,GP_SOURCE,TOTAL_GP_HC,TOTAL_GP_FTE,TOTAL_GP_HC_COQ_UK,TOTAL_GP_HC_COQ_EEA,TOTAL_GP_HC_COQ_EUROPE_OTHER,TOTAL_GP_HC_COQ_AFRICA,TOTAL_GP_HC_COQ_ASIA_OTHER,TOTAL_GP_HC_COQ_ASIA_SOUTH,TOTAL_GP_HC_COQ_AUS_PAC,TOTAL_GP_HC_COQ_CEN_AMERICA,TOTAL_GP_HC_COQ_NORTH_AMERICA,TOTAL_GP_HC_COQ_SOUTH_AMERICA,TOTAL_GP_HC_COQ_MIDDLE_EAST,TOTAL_GP_HC_COQ_UNKNOWN
532,B83033,MODALITY PARTNERSHIP (AWC),86426,Fully provided,93.0,59.546667,85.0,2.0,1.0,3.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
data[data.PRAC_NAME=='Leighton Road Surgery']

Empty DataFrame
Columns: [PRAC_CODE, PRAC_NAME, TOTAL_PATIENTS, GP_SOURCE, TOTAL_GP_HC, TOTAL_GP_FTE, TOTAL_GP_HC_COQ_UK, TOTAL_GP_HC_COQ_EEA, TOTAL_GP_HC_COQ_EUROPE_OTHER, TOTAL_GP_HC_COQ_AFRICA, TOTAL_GP_HC_COQ_ASIA_OTHER, TOTAL_GP_HC_COQ_ASIA_SOUTH, TOTAL_GP_HC_COQ_AUS_PAC, TOTAL_GP_HC_COQ_CEN_AMERICA, TOTAL_GP_HC_COQ_NORTH_AMERICA, TOTAL_GP_HC_COQ_SOUTH_AMERICA, TOTAL_GP_HC_COQ_MIDDLE_EAST, TOTAL_GP_HC_COQ_UNKNOWN]
Index: []

In [7]:
data.isnull().sum()

PRAC_CODE                         0
PRAC_NAME                         0
TOTAL_PATIENTS                    0
GP_SOURCE                         0
TOTAL_GP_HC                      54
TOTAL_GP_FTE                     54
TOTAL_GP_HC_COQ_UK               54
TOTAL_GP_HC_COQ_EEA              54
TOTAL_GP_HC_COQ_EUROPE_OTHER     54
TOTAL_GP_HC_COQ_AFRICA           54
TOTAL_GP_HC_COQ_ASIA_OTHER       54
TOTAL_GP_HC_COQ_ASIA_SOUTH       54
TOTAL_GP_HC_COQ_AUS_PAC          54
TOTAL_GP_HC_COQ_CEN_AMERICA      54
TOTAL_GP_HC_COQ_NORTH_AMERICA    54
TOTAL_GP_HC_COQ_SOUTH_AMERICA    54
TOTAL_GP_HC_COQ_MIDDLE_EAST      54
TOTAL_GP_HC_COQ_UNKNOWN          54
dtype: int64

In [8]:
data.GP_SOURCE.value_counts()

GP_SOURCE
Fully provided                                5874
Includes FTE Estimates                         221
Fully estimated - no data provided              39
Fully estimated - no valid or current data      15
Name: count, dtype: int64

In [4]:
data[data.GP_SOURCE=='Fully estimated - no data provided']

,PRAC_CODE,PRAC_NAME,TOTAL_PATIENTS,GP_SOURCE,TOTAL_GP_HC,TOTAL_GP_FTE,TOTAL_GP_HC_COQ_UK,TOTAL_GP_HC_COQ_EEA,TOTAL_GP_HC_COQ_EUROPE_OTHER,TOTAL_GP_HC_COQ_AFRICA,TOTAL_GP_HC_COQ_ASIA_OTHER,TOTAL_GP_HC_COQ_ASIA_SOUTH,TOTAL_GP_HC_COQ_AUS_PAC,TOTAL_GP_HC_COQ_CEN_AMERICA,TOTAL_GP_HC_COQ_NORTH_AMERICA,TOTAL_GP_HC_COQ_SOUTH_AMERICA,TOTAL_GP_HC_COQ_MIDDLE_EAST,TOTAL_GP_HC_COQ_UNKNOWN
405,B81085,HAXBY GROUP HULL,39082,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429,B81645,EAST PARK PRACTICE,1942,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
566,B83660,BILTON MEDICAL CENTRE,5561,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
953,C82103,DISHLEY GRANGE MEDICAL PRACTICE,6743,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1186,C84720,NOTSPAR,28,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1319,C88059,HAROLD STREET MEDICAL CENTRE,2442,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1506,D82618,THE WOOTTONS SURGERY,5667,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1781,E84011,ST ANDREWS MEDICAL CENTRE,1632,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2324,F82627,RAINHAM HEALTH CENTRE,7066,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3482,J81631,SANDFORD SURGERY,1950,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3602,J82213,BROOK HOUSE SURGERY,6172,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3878,K83056,COUNTY SURGERY,4081,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4120,L83027,CROFT HALL MEDICAL PRACTICE,7225,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5131,N81642,WATERS EDGE MEDICAL CENTRE,4722,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5205,N82648,POULTER ROAD MEDICAL CENTRE,2806,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5448,P81166,DR BELLO'S SURGERY,2432,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5496,P81726,KING STREET MEDICAL CTR,1915,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5499,P81732,HARAMBEE SURGERY,4580,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5626,P84065,CHURCH VIEW MEDICAL CENTRE,4202,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5871,P92633,BEE FOLD MEDICAL CENTRE,3758,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5978,Y02322,LEIGH FAMILY PRACTICE,9907,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5992,Y02514,LITHERLAND PRIMARY CARE WALK-IN SERVICE,0,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6008,Y02620,THE HILL GENERAL PRACTICE & UCC,0,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6051,Y02886,LEIGH SPORTS VILLAGE,4697,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6074,Y03303,THE RIDGEWAY HEALTH CENTRE,2,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6100,Y05125,CANNOCK PRACTICES NETWORK SURGERY,0,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6102,Y05190,ISLINGTON GP FEDERATION,0,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6105,Y05286,LISTER HOUSE CHELLASTON,2,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6113,Y05472,VULNERABLE ADULTS SERVICE,0,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6119,Y05960,NC GPA PLUS,0,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6125,Y06354,ASPIRO HEALTHCARE,0,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6129,Y06487,BABYLON GP AT HAND BIRMINGHAM,0,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6131,Y06659,NOOK SURGERY,3271,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6141,Y07697,WIGAN BOROUGH SPECIALIST SERVICES,143,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6142,Y07819,SPCL SURGERY,42,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6143,Y08362,SAS WEST HERTS,0,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6144,Y08368,PENVALE PARK MEDICAL CENTRE,0,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6147,Y08645,WAVERLEY MEDICAL CENTRE,0,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6148,Y09077,HEARTBEAT PRIMARY CARE CIC,0,Fully estimated - no data provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
data = data.dropna()

In [15]:
data.sort_values(by='TOTAL_GP_HC',ascending=False)

,PRAC_CODE,PRAC_NAME,TOTAL_PATIENTS,GP_SOURCE,TOTAL_GP_HC,TOTAL_GP_FTE,TOTAL_GP_HC_COQ_UK,TOTAL_GP_HC_COQ_EEA,TOTAL_GP_HC_COQ_EUROPE_OTHER,TOTAL_GP_HC_COQ_AFRICA,TOTAL_GP_HC_COQ_ASIA_OTHER,TOTAL_GP_HC_COQ_ASIA_SOUTH,TOTAL_GP_HC_COQ_AUS_PAC,TOTAL_GP_HC_COQ_CEN_AMERICA,TOTAL_GP_HC_COQ_NORTH_AMERICA,TOTAL_GP_HC_COQ_SOUTH_AMERICA,TOTAL_GP_HC_COQ_MIDDLE_EAST,TOTAL_GP_HC_COQ_UNKNOWN
532,B83033,MODALITY PARTNERSHIP (AWC),86426,Fully provided,93.0,59.546667,85.0,2.0,1.0,3.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
2510,F85002,MEDICUS HEALTH PARTNERS,93741,Includes FTE Estimates,69.0,44.830649,44.0,2.0,1.0,8.0,1.0,11.0,0.0,2.0,0.0,0.0,0.0,0.0
1381,D81043,GRANTA MEDICAL PRACTICES,58583,Includes FTE Estimates,63.0,37.785554,52.0,4.0,0.0,2.0,0.0,4.0,0.0,0.0,0.0,0.0,1.0,0.0
441,B82005,PRIORY MEDICAL GROUP,57287,Includes FTE Estimates,62.0,25.679665,37.0,2.0,0.0,2.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,16.0
4696,M85063,MIDLANDS MEDICAL PARTNERSHIP,54704,Fully provided,58.0,46.917333,36.0,3.0,1.0,7.0,0.0,8.0,0.0,0.0,0.0,0.0,3.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53,A81602,DR RASOOL,2309,Fully provided,1.0,1.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
6135,Y07020,ONE CARE LAMBETH,250,Fully provided,1.0,0.426667,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6130,Y06592,SPECIAL ALLOCATION SCHEME (NEL),208,Fully provided,1.0,0.213333,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6145,Y08371,BEAM PARK MEDICAL PRACTICE,5038,Fully provided,1.0,0.533333,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6146,Y08411,ONE CARE LEWISHAM,326,Fully provided,1.0,0.533333,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0